# Generated by Django 6.0 on 2025-12-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField()),
                ('p_weight', models.FloatField()),
                ('p_price', models.FloatField()),
                ('p_desc', models.TextField()),
                ('p_img', models.ImageField(upload_to='static')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categories')),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flavour')),
            ],
        ),
    ]
