# Generated by Django 6.0 on 2025-12-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_status',
            field=models.BooleanField(default=False),
        ),
    ]
