# Generated by Django 6.0 on 2025-12-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order_o_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transition_id',
            field=models.CharField(null=True),
        ),
    ]
