# Generated by Django 6.0 on 2026-01-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_payment_transition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_star',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
