# Generated by Django 6.0 on 2026-01-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_feedback_feedback_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product', unique=True),
        ),
    ]
