# Generated by Django 6.0 on 2026-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_gallery_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='flavour_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_p1',
            field=models.ImageField(upload_to='product_gallery/img1/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_p2',
            field=models.ImageField(upload_to='product_gallery/img2/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_p3',
            field=models.ImageField(upload_to='product_gallery/img3/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transition_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_img',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(max_length=50),
        ),
    ]
